# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codice Inutile
email: codiceinutile@gmail.com
author: codiceinutile
description: Codice Inutile &egrave; un collettivo di artisti e programmatori nato per esplorare e diffondere la potenzialit&agrave; del codice.
timezone: Europe/Rome

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.codiceinutile.org" # the base hostname & protocol for your site

# Social Settings
newsletter_url: http://eepurl.com/chFYY5

# SEO Settings
# https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: codiceinutile

facebook:
  app_id: 1055775321175305
  publisher: http://www.facebook.com/codiceinutile

github:
  username: codiceinutile

google_site_verification: sXrZY76d0L9dLRhShowTHH7coc-wwVK-E2fE25A6Ibw


# Build settings
markdown: kramdown

# SEO
gems:
  - jekyll-seo-tag
